// GENERATED by scripts/prep-assets.mjs — do not edit by hand.
export interface DerivedAsset {
  readonly src: string;
  readonly width: number;
  readonly height: number;
  /** Emitted widths, ascending. The last entry is the master file. */
  readonly widths: readonly number[];
}

export const ASSETS = {
  'brand/logo': { src: '/brand/logo.webp', width: 1045, height: 314, widths: [480, 720, 1045] },
  'brand/logo-white': { src: '/brand/logo-white.webp', width: 1045, height: 314, widths: [480, 720, 1045] },
  'colors/graphite': { src: '/colors/graphite.webp', width: 329, height: 790, widths: [329] },
  'colors/green': { src: '/colors/green.webp', width: 312, height: 787, widths: [312] },
  'colors/indigo': { src: '/colors/indigo.webp', width: 313, height: 786, widths: [313] },
  'colors/stack': { src: '/colors/stack.webp', width: 1080, height: 1120, widths: [480, 720, 1080] },
  'colors/terracotta': { src: '/colors/terracotta.webp', width: 291, height: 744, widths: [291] },
  'colors/white': { src: '/colors/white.webp', width: 286, height: 764, widths: [286] },
  'hero/silhouette': { src: '/hero/silhouette.webp', width: 1080, height: 1200, widths: [480, 720, 1080] },
  'hero/white': { src: '/hero/white.webp', width: 960, height: 1200, widths: [480, 720, 960] },
  'models/bravo': { src: '/models/bravo.webp', width: 1080, height: 1200, widths: [480, 720, 1080] },
  'models/classic': { src: '/models/classic.webp', width: 1080, height: 1138, widths: [480, 720, 1080] },
  'models/classic-350': { src: '/models/classic-350.webp', width: 1059, height: 1204, widths: [480, 720, 1059] },
  'models/elegant': { src: '/models/elegant.webp', width: 1080, height: 1132, widths: [480, 720, 1080] },
  'models/elegant-premium': { src: '/models/elegant-premium.webp', width: 1080, height: 1180, widths: [480, 720, 1080] },
  'models/infinity': { src: '/models/infinity.webp', width: 1080, height: 1200, widths: [480, 720, 1080] },
  'models/lineup': { src: '/models/lineup.webp', width: 1063, height: 454, widths: [480, 720, 1063] },
  'sections/about-steel': { src: '/sections/about-steel.webp', width: 1080, height: 1190, widths: [480, 720, 1080] },
  'sections/benefits-indigo': { src: '/sections/benefits-indigo.webp', width: 1080, height: 1120, widths: [480, 720, 1080] },
  'sections/capacity-green': { src: '/sections/capacity-green.webp', width: 780, height: 1117, widths: [480, 720, 780] },
  'sections/final-white': { src: '/sections/final-white.webp', width: 1052, height: 1118, widths: [480, 720, 1052] },
  'sections/heat-silver': { src: '/sections/heat-silver.webp', width: 1073, height: 1167, widths: [480, 720, 1073] },
  'sections/interior': { src: '/sections/interior.webp', width: 650, height: 560, widths: [480, 650] },
  'sections/interior-product': { src: '/sections/interior-product.webp', width: 524, height: 516, widths: [480, 524] },
  'sections/qc-white': { src: '/sections/qc-white.webp', width: 570, height: 1455, widths: [480, 570] },
  'sections/tech-indigo': { src: '/sections/tech-indigo.webp', width: 1080, height: 1195, widths: [480, 720, 1080] },
  'sections/warranty-mustard': { src: '/sections/warranty-mustard.webp', width: 600, height: 926, widths: [480, 600] },
} as const satisfies Record<string, DerivedAsset>;

export type AssetId = keyof typeof ASSETS;

export function asset(id: AssetId): DerivedAsset {
  return ASSETS[id];
}
