// GENERATED by scripts/prep-assets.mjs — do not edit by hand.
export interface DerivedAsset {
  readonly src: string;
  readonly width: number;
  readonly height: number;
}

export const ASSETS = {
  'brand/logo': { src: '/brand/logo.webp', width: 1045, height: 314 },
  'brand/logo-white': { src: '/brand/logo-white.webp', width: 1045, height: 314 },
  'colors/graphite': { src: '/colors/graphite.webp', width: 329, height: 790 },
  'colors/green': { src: '/colors/green.webp', width: 312, height: 787 },
  'colors/indigo': { src: '/colors/indigo.webp', width: 314, height: 786 },
  'colors/stack': { src: '/colors/stack.webp', width: 1080, height: 1120 },
  'colors/terracotta': { src: '/colors/terracotta.webp', width: 292, height: 744 },
  'colors/white': { src: '/colors/white.webp', width: 288, height: 767 },
  'hero/silhouette': { src: '/hero/silhouette.webp', width: 1080, height: 1200 },
  'hero/white': { src: '/hero/white.webp', width: 960, height: 1200 },
  'models/bravo': { src: '/models/bravo.webp', width: 1080, height: 1200 },
  'models/classic': { src: '/models/classic.webp', width: 1080, height: 1205 },
  'models/classic-350': { src: '/models/classic-350.webp', width: 1080, height: 1231 },
  'models/elegant': { src: '/models/elegant.webp', width: 1080, height: 1180 },
  'models/elegant-premium': { src: '/models/elegant-premium.webp', width: 1080, height: 1180 },
  'models/infinity': { src: '/models/infinity.webp', width: 1080, height: 1200 },
  'models/lineup': { src: '/models/lineup.webp', width: 1080, height: 480 },
  'sections/about-steel': { src: '/sections/about-steel.webp', width: 1080, height: 1190 },
  'sections/benefits-indigo': { src: '/sections/benefits-indigo.webp', width: 1080, height: 1120 },
  'sections/capacity-green': { src: '/sections/capacity-green.webp', width: 780, height: 1140 },
  'sections/final-white': { src: '/sections/final-white.webp', width: 1060, height: 1145 },
  'sections/heat-silver': { src: '/sections/heat-silver.webp', width: 1080, height: 1185 },
  'sections/interior': { src: '/sections/interior.webp', width: 1080, height: 1165 },
  'sections/qc-white': { src: '/sections/qc-white.webp', width: 570, height: 1455 },
  'sections/tech-indigo': { src: '/sections/tech-indigo.webp', width: 1080, height: 1195 },
  'sections/warranty-mustard': { src: '/sections/warranty-mustard.webp', width: 600, height: 935 },
} as const satisfies Record<string, DerivedAsset>;

export type AssetId = keyof typeof ASSETS;

export function asset(id: AssetId): DerivedAsset {
  return ASSETS[id];
}
